# Generated by Django 6.0 on 2026-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='Standard', max_length=20),
        ),
    ]
