# Generated by Django 6.0 on 2026-01-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_method', models.CharField(choices=[('BOOTH', '下次 Booth 自取'), ('SF', '順豐到付')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CC', '信用卡'), ('PAYME', 'Payme'), ('ALIPAY', '支付寶HK'), ('APPLE', 'Apple Pay')], max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
