# Generated by Django 6.0 on 2026-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_orderitem_size'),
        ('orders', '0002_order_sf_address_order_sf_region_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='orderitems.OrderItem', to='products.product'),
        ),
    ]
