# Generated by Django 6.0 on 2026-01-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('policy_info', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=11, help_text='戒指預設11，其餘預設0')),
                ('image_00', models.ImageField(upload_to='products/')),
                ('image_01', models.ImageField(blank=True, upload_to='products/')),
                ('image_02', models.ImageField(blank=True, upload_to='products/')),
                ('image_03', models.ImageField(blank=True, upload_to='products/')),
                ('image_04', models.ImageField(blank=True, upload_to='products/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
    ]
