# Generated by Django 6.0 on 2026-01-08 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('policy_info', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=11, help_text='戒指預設11，其餘預設0')),
                ('product_type', models.CharField(choices=[('耳環', '耳環'),('戒指', '戒指'), ('手鏈', '手鏈'), ('頸鏈', '頸鏈'), ('媽媽勾織', '媽媽勾織')], default='耳環', max_length=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
        ),
    ]
