# Generated by Django 6.0 on 2026-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('耳環', '耳環'), ('戒指', '戒指'), ('手鏈', '手鏈'), ('頸鏈', '頸鏈'), ('媽媽勾織', '媽媽勾織')], default='戒指', max_length=10),
        ),
    ]
