# Generated by Django 6.0 on 2026-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(default=11),
        ),
    ]
