# Generated by Django 6.0 on 2026-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Standard', max_length=20),
        ),
    ]
