# Generated by Django 6.0 on 2026-01-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': '聯絡訊息', 'verbose_name_plural': '聯絡訊息管理'},
        ),
    ]
