# Generated by Django 6.0 on 2026-01-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category_type', models.CharField(choices=[('耳環', '耳環'), ('戒指', '戒指'), ('手鏈', '手鏈'), ('頸鏈', '頸鏈'), ('媽媽勾織', '媽媽勾織')], default='耳環', help_text='選擇呢個分類屬於邊種產品，會影響 Size 嘅預設邏輯', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='categories__created_6b010e_idx')],
            },
        ),
    ]
