# Generated by Django 6.0 on 2026-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('耳環', '耳環'), ('戒指', '戒指'), ('手鏈', '手鏈'), ('頸鏈', '頸鏈'), ('媽媽勾織', '媽媽勾織')], default='耳環', help_text='選擇呢個分類屬於邊種產品，會影響 Size 嘅預設邏輯', max_length=20),
        ),
    ]
